"""What the laboratory actually computes, written for the in-app methods panel.

Lines written entirely in capitals are drawn as section headings.
"""

METHODS = """
SMLab generates leading-order Standard Model collisions and draws them in a schematic solenoidal detector. It is a teaching instrument built on published formulas, not a substitute for MadGraph, Whizard, PYTHIA, or Geant4. Every input and formula below has a source; every approximation is listed.

INPUTS
Masses, widths, lifetimes, tau branching fractions, and CKM magnitudes are from the 2026 Review of Particle Physics: F. Takahashi et al. (Particle Data Group), Int. J. Mod. Phys. A 41, 2630011 (2026). Key values: M_Z = 91.1879 GeV, Γ_Z = 2.4955 GeV, M_W = 80.3625 GeV, Γ_W = 2.14 GeV, M_H = 125.13 GeV, m_t = 172.60 GeV (direct measurements), Γ_t = 1.42 GeV.
Fundamental constants are CODATA 2022 as tabulated by the PDG: α⁻¹(0) = 137.035999177 and (ħc)² = 0.3893793721 GeV² mb. The Fermi constant is the PDG 2026 value, G_F = 1.1663785×10⁻⁵ GeV⁻² (CODATA 2022 lists 1.1663787×10⁻⁵). α_s(M_Z) = 0.1180 is the PDG world average. The weak mixing angle in the couplings is the effective leptonic value sin²θ_eff = 0.23154, the Standard Model fit value of the PDG Electroweak review (the measured average is 0.23148 ± 0.00012), and the hadronic vacuum polarization is Δα_had⁽⁵⁾(M_Z²) = 0.02760, both from the PDG Electroweak review (the latter from M. Davier et al., Eur. Phys. J. C 80, 241 (2020)).
Quark masses: u, d, s are MS-bar values at 2 GeV, c and b are MS-bar m(m), and top is the direct-measurement average. They set kinematic thresholds only.

RUNNING COUPLINGS
α(s) = α(0) / (1 − Δα_lep(s) − Δα_had(s)). The lepton loops are the one-loop leading-log sum (α/3π) Σ [ln(s/m²) − 5/3]. The hadronic part is the PDG Δα_had⁽⁵⁾(M_Z²) moved to other energies with the perturbative five-flavor quark loop; this is approximate below about 10 GeV. The result is α(M_Z²)⁻¹ = 128.95.
α_s(Q) is one-loop running from α_s(M_Z), with the number of flavors changing at m_c, m_b, and m_t and α_s continuous across each threshold.

FERMION PAIRS
e⁺e⁻ → f f̄, and the parton-level Drell–Yan process q q̄ → f f̄, use the improved Born approximation: photon exchange with α(s), Z exchange normalized with G_F, and their interference. This is the Born-type structure with effective couplings used in the LEP/SLD Z-pole analyses (ALEPH, DELPHI, L3, OPAL, SLD Collaborations et al., Phys. Rept. 427, 257 (2006), arXiv:hep-ex/0509008, §1.5). The reduced propagator is

χ(s) = [G_F M_Z² / (2√2 π α(s))] · s / (s − M_Z² + i s Γ_Z / M_Z)

with g_A = T₃ and g_V = T₃ − 2Q sin²θ_eff. On the Z pole this reproduces the Breit–Wigner built from the same partial widths. For massive final fermions the vector part scales as β(3−β²)/2, the axial part as β³, and the forward–backward (vector × axial) part as β². Quark final states carry N_c and the massless O(α_s) factor 1 + α_s(s)/π. θ is the angle between the incoming fermion and the outgoing fermion.
Check: the muon-pair pole cross section here is 1.98 nb; the LEP pole fit gives σ⁰_had / R_μ = 41.480 nb / 20.784 = 2.00 nb (PDG Electroweak review). With initial-state radiation the peak falls to 1.46 nb.

NEUTRINO PAIRS
e⁺e⁻ → ν_e ν̄_e (and μ⁺μ⁻ → ν_μ ν̄_μ) also proceed through t-channel W exchange. After a Fierz rearrangement the W adds to the left-handed Z amplitude:

dσ/dΩ = (G_F² s / 32π²) [ |g_L P_Z(s) + P_W(t)|² (1+cosθ)² + g_R² |P_Z(s)|² (1−cosθ)² ]

with P_Z = M_Z²/(M_Z² − s − i sΓ_Z/M_Z), P_W = M_W²/(M_W² − t), g_L = −½ + sin²θ_eff, g_R = sin²θ_eff. At low energy this is σ = G_F² s/(6π) [(g_L+1)² + g_R²], the same "+1" as in ν_e e scattering. Other neutrino flavors have only the Z.

INITIAL-STATE RADIATION
For lepton beams the Born cross section is folded with the O(β) leading-log Kuraev–Fadin radiator (E. A. Kuraev and V. S. Fadin, Sov. J. Nucl. Phys. 41, 466 (1985)):

H(v) = β v^(β−1) (1 + 3β/4) − β (1 − v/2),   β = (2α/π)(ln(s/m²) − 1)

where v is the fraction of the energy carried by the photons. One collinear photon represents that radiation. It escapes down the beam pipe, the hard scale becomes s′ = s(1−v), and the hard system recoils. The integration grid resolves the Z line shape and the 1/s′ rise at large v, so radiative return above the Z is computed accurately. Quark beams have no radiator.

BHABHA AND TWO PHOTONS
e⁺e⁻ → e⁺e⁻ is the QED Born cross section with photon exchange in the s and t channels (M. E. Peskin, D. V. Schroeder, An Introduction to Quantum Field Theory, Addison-Wesley (1995), Problem 5.2), cut to 10° < θ < 170° so the forward pole is finite. The Z diagrams of Bhabha are omitted, so do not read a Z-pole asymmetry from this channel. e⁺e⁻ → γγ uses the massless QED result with the identical-photon factor 1/2 and the same angular cut.

HIGGSSTRAHLUNG
e⁺e⁻ → ZH uses the Born formula

σ = [G_F² M_Z⁴ / (96π s)] (v_e² + a_e²) λ^½ (λ + 12 M_Z²/s) / (1 − M_Z²/s)²

with a_e = −1 and v_e = −1 + 4 sin²θ_eff (W. Kilian, M. Krämer, P. M. Zerwas, Phys. Lett. B 373, 135 (1996), eq. 2; A. Djouadi, Phys. Rept. 457, 1 (2008), eq. 4.18). The Z angular weight is λ sin²θ + 8 M_Z²/s. At 250 GeV this gives 238 fb at Born level and about 210 fb with ISR. For comparison, the one-loop electroweak calculation of S. Bondarenko et al., Phys. Rev. D 100, 073002 (2019), quotes 225.6 fb (Born, α(0) scheme, older inputs) and 206.9 fb at one loop.

DECAYS
Z partial widths come from the same couplings; W partial widths use the PDG CKM magnitudes, a factor 1 + α_s/π for quarks, and the exact tree-level mass factor for massive daughters. This gives BR(Z → ℓℓ) ≈ 3.36% and BR(W → ℓν) ≈ 10.8% per lepton flavour, as measured: (3.3658 ± 0.0023)% and (10.86 ± 0.09)% in PDG 2026.
Higgs branching fractions are the Standard Model table of the LHC Higgs Cross Section Working Group (CERN Yellow Report 4, CERN-2017-002-M) at m_H = 125.10 GeV, renormalized to one. H → WW* and H → ZZ* sample the virtual masses from q² Breit–Wigners times phase space and the H → VV matrix element (Djouadi, above).
Tau decays use PDG 2026 fractions for eνν, μνν, πν, π π⁰ν (through the ρ), 3π ν (through the a₁), and π⁻π⁺π⁻π⁰ν. The remaining 5.6% (kaon modes, π⁻3π⁰ν, higher multiplicity) is represented by a charge-conserving one-prong four-pion state. Leptonic muon and tau decays use the Michel spectrum (L. Michel, Proc. Phys. Soc. A 63, 514 (1950)). W, Z, and Higgs decay angles are isotropic in the parent rest frame: spin correlations are not simulated. Muons are stable unless “Muons decay” is on, which matches a real tracker (cτ_μ = 659 m).

TIMES
A mean life is cτ/c from the PDG, or ħ/Γ from the PDG width. The Higgs entry uses the Standard Model width 4.10 MeV (LHC HXSWG), not the loosely measured width (PDG 2026: 3.0 +1.5 −0.7 MeV). Quarks other than the top, and gluons, are partons and have no free-particle lifetime in this program. The approach on screen is slowed so the paths can be watched. The hard-scatter time scale is ħ/√s′, not the length of that picture.

DETECTOR
Charged tracks obey p_T = 0.299792458 |q| B R in a uniform 3.8 T field along the beam, the CMS operating field. Positive charges curve clockwise in the transverse view. The layering — tracker, ECAL, HCAL, solenoid, muon stations — is a schematic barrel, not a Geant4 geometry. There is no material interaction, no resolution smearing, and no shower. Quarks and gluons are drawn as partons. Neutrinos appear only as missing transverse momentum.
The 3D view draws the same barrel. A charged track is a helix: the transverse circle is the formula above, and the distance along the field is (p_z / p_T) times the arc length. Straight tracks run until they meet a cylinder wall or the end of that layer. Inner half-lengths are R sinh(1.5). The gold coil is 12.5 m long with a 6 m bore, the CMS solenoid (V. Klyukhin et al., arXiv:2201.07557).

CUSTOM INCOMING STATE
Custom chooses the two incoming particles, a momentum for each, and the angle between those momenta. 180° is head-on. Speed is β = |p|/E and is displayed; it is not a separate dial, because mass and momentum already fix it. √s is the invariant mass of the two 4-vectors. Products are generated with the same formulas as the preset beams, in the center of mass, then rotated and boosted into the lab frame you defined. Pairs without a formula — anything other than e⁻e⁺, μ⁻μ⁺, or a quark with its antiquark — are drawn as incoming rays only.

RESEARCH-GRADE ENGINE: PYTHIA 8.3
The PYTHIA 8.3 switch in the top bar replaces the built-in Born generator with PYTHIA 8.312 (C. Bierlich et al., "A comprehensive guide to the physics and usage of PYTHIA 8.3", SciPost Phys. Codebases 8 (2022), arXiv:2203.11601), running in WSL. PYTHIA generates the hard process at leading order and adds everything around it: QED and QCD initial- and final-state showers, multiparton interactions and beam remnants in proton collisions, Lund string hadronization (B. Andersson, G. Gustafson, G. Ingelman, T. Sjöstrand, Phys. Rept. 97, 31 (1983)), and the decays of hadrons and τ leptons with their measured branching fractions.
Settings are PYTHIA's defaults with the Monash 2013 tune (P. Skands, S. Carrazza, J. Rojo, Eur. Phys. J. C 74, 3024 (2014), arXiv:1404.5630). Proton collisions use the NNPDF2.3 QCD+QED LO parton distributions of that tune (R. D. Ball et al., Nucl. Phys. B 877, 290 (2013)); LHAPDF 6 (A. Buckley et al., Eur. Phys. J. C 75, 132 (2015)) is installed for other sets. Lepton beams radiate through PYTHIA's QED structure functions. The Z, W, Higgs, top, and τ masses and widths and sin²θ_eff are set to the PDG 2026 values above. A particle decays only if its sampled decay point lies inside the tracker (R < 1.2 m), so K⁰_S, Λ, charm and bottom hadrons decay at their real, displaced vertices, while longer-lived particles reach the calorimeters.
Cross sections are PYTHIA's leading-order estimates, with their statistical uncertainty from the events generated so far. Higher-order corrections are not applied, so measured rates can be larger: the t t̄ cross section measured at 13.6 TeV, 850 ± 27 pb (ATLAS, Phys. Lett. B 848 (2024) 138376) and 881 ± 30 pb (CMS, JHEP 08 (2023) 204), is 1.4–1.5 times PYTHIA's leading-order 602 pb.
Jets are clustered with FastJet 3.5 (M. Cacciari, G. P. Salam, G. Soyez, Eur. Phys. J. C 72, 1896 (2012)): anti-kT with R = 0.4, pT > 20 GeV, |η| < 4.7 for protons (JHEP 04 (2008) 063), and the e⁺e⁻ Durham algorithm with y_cut = 0.005 for lepton beams (S. Catani, Yu. L. Dokshitzer, M. Olsson, G. Turnock, B. R. Webber, Phys. Lett. B 269, 432 (1991)).

DETECTOR SIMULATION: DELPHES
With "Detector simulation" on, each event is written in HepMC3 format (A. Buckley et al., Comput. Phys. Commun. 260, 107310 (2021)) and passed through Delphes 3.5.1 (J. de Favereau et al., JHEP 02 (2014) 057, arXiv:1307.6346), the standard fast simulation of collider detectors. The card follows the collider: CMS for proton beams, ALEPH at LEP energies (√s ≤ 209 GeV), IDEA for FCC-ee (≤ 400 GeV), CLICdet above that, and the muon-collider detector for μ⁺μ⁻. Delphes applies each detector's measured tracking and calorimeter resolutions, identification and isolation efficiencies, and b-tagging, and reconstructs electrons, muons, photons, jets, and missing transverse momentum; those reconstructed objects then replace the generator-level ones on screen. As a check, 87 % of generated muons inside the CMS acceptance (|η| < 2.4, pT > 10 GeV) are reconstructed in Drell–Yan events, consistent with the card's identification efficiency and isolation requirement.

PILEUP
For proton beams with detector simulation on, Delphes' CMS pileup card overlays a Poisson-distributed number of additional minimum-bias collisions (mean ⟨μ⟩ = 30, 60, or 140) on every event, spread along the beam with the card's longitudinal and timing profile. The minimum-bias library is 5000 PYTHIA inelastic events at the same energy (Monash tune), built once and cached. Pileup tracks are identified and drawn in grey from their own vertices. The card subtracts charged pileup from jets and missing momentum; neutral pileup energy remains, so the missing-momentum resolution degrades with μ (in Z → ℓℓ events the mean missing pT is 17, 36, and 50 GeV at μ = 0, 30, and 60), somewhat worse than CMS achieves with its more advanced pileup mitigation.

NEXT-TO-LEADING ORDER: MADGRAPH5_AMC@NLO
For t t̄, Drell–Yan Z/γ* → ℓℓ, and W → ℓν in proton collisions, samples generated with MadGraph5_aMC@NLO 3.5.7 (J. Alwall et al., JHEP 07 (2014) 079, arXiv:1405.0301) at next-to-leading order in QCD replace PYTHIA's leading-order hard process. They are matched to the PYTHIA 8 shower with the MC@NLO method (S. Frixione, B. Webber, JHEP 06 (2002) 029) using MadGraph's own PYTHIA 8 matching settings, with NNPDF3.1 NLO parton distributions (NNPDF Collaboration, R. D. Ball et al., Eur. Phys. J. C 77, 663 (2017); LHAPDF 303400). Inputs follow PDG 2026: m_t = 172.60 GeV, M_Z = 91.1879 GeV, the listed widths, and α⁻¹ = 132.04 so that the G_F scheme reproduces M_W = 80.36 GeV. The displayed cross section is the NLO value with its renormalization- and factorization-scale uncertainty. About a fifth of MC@NLO events have negative weights; histograms use the signed weights. Samples exist for the energies generated with hep/mg5/generate_nlo.sh: at 13 TeV, σ(t t̄) = 663 pb and σ(Z/γ* → ℓℓ, m_ℓℓ > 60 GeV, e + μ) = 3.69 nb; at 13.6 TeV, 737 pb, 3.87 nb, and σ(W → ℓν, e + μ) = 38.9 nb, each with a scale uncertainty of about +6 to +10 % / −10 to −12 %.
Top quarks in the t t̄ samples are decayed by MadSpin (P. Artoisenet, R. Frederix, O. Mattelaer, R. Rietkerk, JHEP 03 (2013) 015, arXiv:1212.3460) with the full tree-level t → W b → f f′ b matrix element, which keeps the spin correlation between the t and t̄; PYTHIA then showers the decay products. The tops are decayed on their mass shell (m_t = 172.6 GeV) while the W keeps its Breit–Wigner: MadSpin's off-shell mode was tested against MadGraph's full t t̄ → bW bW matrix element with identical inputs and shifted the top line shape by +0.43 GeV, whereas the 1.4 GeV top width that on-shell decays leave out is far below detector resolution. The spin correlation is verified in the events themselves: the opening-angle coefficient D = −3⟨cos φ⟩ between the charged leptons in the t and t̄ rest frames agrees with the Standard Model prediction of −0.24 at 13 TeV (NLO QCD with weak corrections; from Table 7 and Eq. 4.23 of W. Bernreuther, D. Heisler, Z.-G. Si, JHEP 12 (2015) 026), while uncorrelated decays would give 0. MadSpin's branching ratios are tree level: W → ℓν is 1/9 = 11.1 % per lepton flavour against the measured 10.86 % (PDG 2026), so dileptonic rates are about 5 % high. PYTHIA's own top and W widths are set to the PDG values (1.42 and 2.14 GeV); for the Z, PYTHIA computes the width from its couplings (2.504 GeV, 0.34 % above the PDG 2.4955 GeV). Against data, MadSpin improves the CMS t t̄ event variables (JHEP 06 (2018) 002) from χ²/ndf 2.51 to 2.01. The ATLAS eμ measurement (Eur. Phys. J. C 80 (2020) 528) cannot separate correlated from uncorrelated decays at this sample size: only about 1 t t̄ event in 60 passes its selection, so the simulation's statistical error per bin is several times the data's.
Against data, NLO improves the CMS t t̄ event variables (median χ²/ndf 7.92 → 2.51). For the Drell–Yan sample at 13 TeV, the Z + 0, 1, and 2 jet processes are each generated at NLO and merged with the FxFx method (R. Frederix, S. Frixione, JHEP 12 (2012) 061, arXiv:1209.6215) at a merging scale of 20 GeV (matrix-element cut 10 GeV), using PYTHIA's own FxFx jet-matching veto (Pythia8Plugins/JetMatching.h, attached to the Python interface by hep/ext/smlab_fxfx.cpp). The veto removes the double counting between the jet multiplicities: about 56 % of the generated events are rejected, and the merged cross section σ(Z/γ* → ℓℓ, m_ℓℓ > 60 GeV, e + μ) = 4.20 nb is PYTHIA's estimate after the veto. An inclusive MC@NLO Z sample describes the ATLAS Z transverse momentum (Eur. Phys. J. C 80 (2020) 616) poorly (χ²/ndf 25.8: above about 100 GeV it is only leading-order Z + 1 jet), worse than PYTHIA at leading order with matrix-element corrections (4.2); with FxFx merging the tail is NLO accurate (6.4).

SHOWER TUNE: SMLAB-AZ 2026
Below about 30 GeV the Z transverse momentum is set by the Sudakov region of the initial-state shower and by the intrinsic transverse momentum of the partons, which MadGraph's standard MC@NLO shower settings do not fit. Following the ATLAS AZNLO method (JHEP 09 (2014) 145), hep/tune.py re-fits the two non-perturbative parameters that control it, keeping the shower α_s at 0.118 as the matching requires: BeamRemnants:primordialKThard (intrinsic kT, Monash 1.8 GeV) and SpaceShower:pT0Ref (Monash 2.0 GeV). Each point of a 5 × 4 grid showers the same 60 000 FxFx events and is compared with the shape of the ATLAS Z transverse-momentum measurement (Eur. Phys. J. C 80 (2020) 616) for pT(ℓℓ) < 30 GeV and φ*_η < 0.3 (38 bins). The data prefer SpaceShower:pT0Ref at its lower limit of 0.5 GeV (ATLAS's AZ tune found 0.59) and, along that row, primordialKThard = 3.04 ± 0.17 GeV (quadratic fit, Δχ² = 1); χ² falls from 259 (Monash) to 45 for 38 bins. A 3 GeV intrinsic kT is larger than the Fermi motion of partons in a proton: it is an effective parameter that also absorbs soft radiation missing from a shower with α_s = 0.118 at one loop. The tune is used with every NLO sample (switch "SMLab-AZ 2026 shower tune"), never at leading order, where PYTHIA's Monash tune applies. Over the whole ATLAS Z spectrum, FxFx with the tune gives χ²/ndf 1.65 in pT(ℓℓ) and 1.57 in φ*_η (untuned: 6.4 and 2.9); the low-pT part was used in the fit, so that is not an independent test. The t t̄ data were not used in the tune: with it, the CMS event variables go from 2.01 to 1.82 and the ATLAS eμ distributions from 0.97 to 1.19, both within the MC statistical precision of these comparisons.

VALIDATION AGAINST DATA: RIVET
The Validation panel compares SMLab's events with published measurements through Rivet 4.1 (C. Bierlich et al., SciPost Phys. Codebases 36 (2024), arXiv:2404.15984; Rivet 3: SciPost Phys. 8, 026 (2020)) and YODA 2 (A. Buckley et al., SciPost Phys. Codebases 45 (2025), arXiv:2312.15070), using each analysis's reference data from HEPData (E. Maguire, L. Heinrich, G. Watt, J. Phys. Conf. Ser. 898, 102006 (2017)). Benchmarks: ALEPH event shapes and multiplicities at the Z pole (Phys. Rept. 294 (1998) 1), ATLAS minimum-bias charged particles at 13 TeV (Phys. Lett. B 758 (2016) 67, arXiv:1602.01633), the ATLAS Z-boson transverse momentum at 13 TeV (Eur. Phys. J. C 80 (2020) 616), CMS t t̄ event variables at 13 TeV (CMS-TOP-16-014, JHEP 06 (2018) 002, arXiv:1803.03991), ATLAS dileptonic eμ t t̄ lepton distributions at 13 TeV (Eur. Phys. J. C 80 (2020) 528), and the CMS inclusive jet cross section at 13 TeV (Eur. Phys. J. C 76 (2016) 451). Each distribution is scored with χ²/ndf = (1/N) Σ (MC − data)² / (σ²_data + σ²_MC), with total data uncertainties, and separately for shape (MC scaled to the data integral) and rate (the MC/data integral). For validation, particles decay with PYTHIA's standard table, the convention of particle-level measurements. Where several generators exist for a benchmark (leading order, MC@NLO, MadSpin, FxFx, and with the SMLab tune), they are overlaid, each with its own χ². A χ² marked * is limited by MC statistics: the simulation's statistical error exceeds the data's in most bins (or a bin with data has no simulated events). There a χ²/ndf near 1 means consistent within the simulation's statistics, not agreement at the precision of the data; a large χ² still shows a real disagreement.

NOT INCLUDED
In the built-in engine: parton showers, hadronization, parton distribution functions, final-state radiation, e⁺e⁻ → W⁺W⁻, ZZ, and vector-boson fusion (all supplied by the PYTHIA engine). In both engines: beam polarization, beamstrahlung, one-loop electroweak corrections, and resummed threshold QCD for t t̄ within a few GeV of threshold. NLO QCD is available only for the processes and energies with a MadGraph5_aMC@NLO sample; their top-quark decays (MadSpin) are tree level. Quark beams are single partons, as inside a hadron collider, not protons: a proton is not an elementary initial state in this Born treatment.
""".strip()
