"""Hadronica's PYTHIA mode against PYTHIA run directly (hep/compare/pythia_direct.cc).

    ~/micromamba/envs/smlab-hep/bin/python hep/compare/pythia_direct.py [--scale 1.0]

For every leading-order validation benchmark, the PYTHIA settings are taken
from Hadronica's own worker (so both runs configure PYTHIA identically; PYTHIA 8.3:
C. Bierlich et al., SciPost Phys. Codebases 8 (2022), arXiv:2203.11601), and the
events are generated by a stand-alone C++ program that hands them to Rivet
through PYTHIA's own HepMC3 interface, bypassing Hadronica's worker, event
serialization, HepMC conversion, and weight handling. The seeds differ from
Hadronica's, so the two samples are statistically independent. For each histogram
the script reports χ²/ndf of the direct run against the data (to set beside
Hadronica's) and of Hadronica against the direct run, with both MC errors: that
should be ≈ 1 if Hadronica's layers change nothing. Writes pythia_direct.json.
"""

from __future__ import annotations

import argparse
import json
import math
import multiprocessing as mp
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
HEP = os.path.dirname(HERE)
sys.path.insert(0, HEP)

import validate  # noqa: E402

ENV = sys.prefix
CXX = os.path.join(ENV, "bin", "x86_64-conda-linux-gnu-g++")
EXE = os.path.join(tempfile.gettempdir(), "smlab_pythia_direct")
LO_BENCHMARKS = ("lep_z_hadrons", "lhc_minbias", "lhc_z_pt", "lhc_ttbar", "lhc_jets")


# conda-forge's fastjet-cxx 3.5.1 ships the library without C++ headers; hep/mg5/setup_mg5.sh
# builds the same version (3.5.1) from source into the MadGraph environment, whose headers match.
FASTJET_HEADERS = os.path.expanduser("~/micromamba/envs/smlab-mg5/include/fastjet")


def build() -> None:
    flags = subprocess.run([os.path.join(ENV, "bin", "rivet-config"), "--cppflags", "--ldflags", "--libs"],
                           capture_output=True, text=True, check=True).stdout.split()
    includes = os.path.join(tempfile.gettempdir(), "smlab_fastjet_headers")
    os.makedirs(includes, exist_ok=True)
    link = os.path.join(includes, "fastjet")
    if not os.path.exists(link):
        os.symlink(FASTJET_HEADERS, link)  # only fastjet/, nothing else from that environment
    subprocess.run([CXX, "-O2", "-std=c++17", os.path.join(HERE, "pythia_direct.cc"), "-o", EXE,
                    f"-I{ENV}/include", f"-I{includes}", *flags, f"-L{ENV}/lib", "-lpythia8", "-lHepMC3",
                    f"-Wl,-rpath,{ENV}/lib"], check=True)


def settings_for(bench: dict) -> list[str]:
    """Exactly the PYTHIA settings Hadronica's worker uses for this benchmark (validation mode)."""
    from worker import Worker

    info = Worker().init({**bench["config"], "seed": 1, "decays": "generator"})
    return [line for line in info["settings"] if not line.startswith("Random:")]


def _chunk(args) -> str:
    cmnd, analyses, n, seed, out = args
    subprocess.run([EXE, cmnd, ",".join(analyses), str(n), str(seed), out], check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return out


def run_direct(bench: dict, scale: float, work: str, seed_base: int = 424242) -> str:
    cmnd = os.path.join(work, f"{bench['key']}.cmnd")
    with open(cmnd, "w", encoding="utf-8") as handle:
        handle.write("\n".join(settings_for(bench)) + "\n")
    total = int(bench["events"] * scale)
    workers = max(1, min(mp.cpu_count() - 2, 30))
    jobs = [(cmnd, bench["analyses"], n, seed_base + 1013 * i, os.path.join(work, f"{bench['key']}_{i}.yoda"))
            for i, (n, _offset) in enumerate(validate.chunk_plan(total, workers))]
    with mp.Pool(workers) as pool:
        outputs = pool.map(_chunk, jobs)
    merged = os.path.join(work, f"{bench['key']}_direct.yoda")
    subprocess.run([os.path.join(ENV, "bin", "rivet-merge"), "-e", "-o", merged, *outputs], check=True,
                   stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    return merged


def mc_vs_mc(smlab_file: str, direct_file: str) -> dict[str, tuple[float, int]]:
    """χ²/ndf between the two MC histograms, with both statistical errors."""
    import yoda

    a, b = yoda.read(smlab_file), yoda.read(direct_file)
    out = {}
    for path, ao in a.items():
        if path.startswith("/RAW") or path not in b:
            continue
        ea, eb = validate._estimate(ao), validate._estimate(b[path])
        if ea is None or eb is None or len(ea[1]) != len(eb[1]):
            continue
        rows = [(x, sx, y, sy) for x, sx, y, sy in zip(ea[1], ea[2], eb[1], eb[2])
                if math.isfinite(x) and math.isfinite(y) and sx * sx + sy * sy > 0.0]
        if rows:
            out[path] = (sum((x - y) ** 2 / (sx * sx + sy * sy) for x, sx, y, sy in rows) / len(rows), len(rows))
    return out


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--scale", type=float, default=1.0, help="fraction of each benchmark's events")
    parser.add_argument("--only", nargs="*", default=None, help="benchmark keys to run")
    parser.add_argument("--keep", default=None, help="directory to keep the direct runs' YODA files in")
    parser.add_argument("--seed-base", type=int, default=424242, help="first random seed (a control run uses another)")
    args = parser.parse_args()
    os.environ["PATH"] = os.path.join(ENV, "bin") + os.pathsep + os.environ.get("PATH", "")
    from worker import XMLDIR

    os.environ["PYTHIA8DATA"] = XMLDIR  # the same PYTHIA data directory the Hadronica worker uses
    build()
    results = json.load(open(os.path.join(HEP, "validation", "results.json"), encoding="utf-8"))["benchmarks"]
    report = {}
    with tempfile.TemporaryDirectory(prefix="smlab-direct-") as work:
        for bench in validate.BENCHMARKS:
            if bench["key"] not in LO_BENCHMARKS or (args.only and bench["key"] not in args.only):
                continue
            direct = run_direct(bench, args.scale, work, args.seed_base)
            if args.keep:
                os.makedirs(args.keep, exist_ok=True)
                subprocess.run(["cp", direct, args.keep], check=True)
            vs_data = {p["path"]: p["chi2_ndf"] for p in validate.compare(direct, bench["analyses"])}
            smlab = {p["path"]: p["chi2_ndf"] for p in results[bench["key"]]["plots"]}
            between = mc_vs_mc(os.path.join(HEP, "validation", f"{bench['key']}.yoda"), direct)
            rows = []
            for path in sorted(set(vs_data) & set(smlab)):
                chi2, ndf = between.get(path, (float("nan"), 0))
                rows.append({"path": path, "smlab_vs_data": smlab[path], "direct_vs_data": vs_data[path],
                             "smlab_vs_direct": chi2, "ndf": ndf})
            all_between = [chi2 for chi2, _ndf in between.values()]
            report[bench["key"]] = {"plots": rows, "median_smlab_vs_direct": validate._median(all_between),
                                    "n_mc_histograms": len(all_between)}
            med = lambda key: validate._median([r[key] for r in rows])  # noqa: E731
            print(f"{bench['key']:15s} data χ²/ndf: Hadronica {med('smlab_vs_data'):.2f}  direct {med('direct_vs_data'):.2f}"
                  f"   Hadronica vs direct: median χ²/ndf {report[bench['key']]['median_smlab_vs_direct']:.2f}"
                  f" over {len(all_between)} histograms", flush=True)
    # A control run with other seeds must not overwrite the main comparison.
    name = "pythia_direct.json" if args.seed_base == 424242 else f"pythia_direct_seed{args.seed_base}.json"
    with open(os.path.join(HERE, name), "w", encoding="utf-8") as handle:
        json.dump(report, handle, indent=1)


if __name__ == "__main__":
    main()
