#!/usr/bin/env bash
# Decay the top quarks of an MC@NLO t t~ sample with MadSpin (standalone).
#
#   decay_madspin.sh <sample name, e.g. ttbar_ms_13000> [generation seconds]
#
# MadSpin (Artoisenet, Frederix, Mattelaer, Rietkerk, JHEP 03 (2013) 015)
# decays t -> W b -> f f' b with the full tree-level matrix element, keeping the
# spin correlations between t and t~. PYTHIA then showers the decayed events.
#
# Spin mode "onshell" (default; SPINMODE=madspin to override): t and W on their
# mass shells (W decays keep their full Breit-Wigner, generated by MadEvent).
# MadSpin 3.5.7's off-shell mode ("madspin") was tested against
# MadGraph's full LO t t~ -> b W b W matrix element with identical inputs: the
# full calculation gives a symmetric Breit-Wigner at m_t = 172.6 GeV (median
# 172.62, 3589 vs 3606 events within 1 width below/above), while MadSpin's
# off-shell mode peaked at 173.03 GeV with twice as many tops above the pole as
# below. On-shell decays avoid that 0.43 GeV bias; the 1.4 GeV top width they
# drop is far below detector resolution.
# Reads ~/hadronica-cache/nlo/<sample>.mg5/Events/run_01/events.lhe[.gz] and writes
# ~/hadronica-cache/nlo/<sample>/events.lhe + info.json.
set -euo pipefail
HERE=$(cd "$(dirname "$0")" && pwd)
NAME="$1"
GEN_SECONDS="${2:-0}"
M=$HOME/micromamba/envs/hadronica-mg5
export PATH=$M/bin:$PATH
# MadSpin compiles its matrix elements with f2py, whose numpy.distutils backend
# fails with setuptools >= 65; Python 3.11's own distutils still works.
export SETUPTOOLS_USE_DISTUTILS=stdlib
OUT=$HOME/hadronica-cache/nlo/$NAME
RUN="$OUT.mg5/Events/run_01"
PROC="${NAME%_*}"
SQRT_S="${NAME##*_}"

WORK=$(mktemp -d)
if [ -f "$RUN/events.lhe.gz" ]; then
    gunzip -c "$RUN/events.lhe.gz" > "$WORK/events.lhe"
else
    cp "$RUN/events.lhe" "$WORK/events.lhe"
fi
cp "$WORK/events.lhe" "$WORK/undecayed.lhe"
cat > "$WORK/madspin_card.dat" <<MS
import $WORK/events.lhe
set max_weight_ps_point 400
set Nevents_for_max_weight 250
set spinmode ${SPINMODE:-onshell}
set BW_cut 15
set seed 20260923
decay t > w+ b, w+ > all all
decay t~ > w- b~, w- > all all
launch
MS
START=$(date +%s)
cd "$WORK"
"$M/MG5_aMC/MadSpin/madspin" "$WORK/madspin_card.dat" > "$OUT.madspin.log" 2>&1
DECAYED=$(ls "$WORK"/events_decayed.lhe* 2>/dev/null | head -1)
[ -n "$DECAYED" ] || { echo "MadSpin produced no events; see $OUT.madspin.log"; exit 1; }
mkdir -p "$OUT"
case "$DECAYED" in
    *.gz) gunzip -c "$DECAYED" > "$OUT/events.lhe" ;;
    *) mv "$DECAYED" "$OUT/events.lhe" ;;
esac
# On-shell MadSpin scales every weight by a constant branching-ratio artifact; undo it.
FACTOR=$("$M/bin/python" "$HERE/restore_weights.py" "$WORK/undecayed.lhe" "$OUT/events.lhe")
SECONDS_TOTAL=$(( GEN_SECONDS + $(date +%s) - START ))
"$M/bin/python" "$HERE/sample_info.py" "$OUT" "$PROC" "$SQRT_S" "$SECONDS_TOTAL" "$OUT.log"     "{\"madspin\": true, \"spinmode\": \"${SPINMODE:-onshell}\", \"madspin_weight_factor_removed\": $FACTOR}"
cd /
rm -rf "$WORK"
